version: '3'

services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    restart: unless-stopped
    ports:
      - ${NEXUS_WEB_PORT}:8081
    volumes:
      - ${NEXUS_MOUNT_DIR}:/nexus-data
