version: '3'

services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr:3.0.9
    container_name: sonarr
    restart: unless-stopped
    environment:
      PUID: ${APP_PUID}
      PGID: ${APP_PGID}
      TZ: ${HOST_TZ}
    volumes:
      - ${SONARR_CONFIG_MOUNT_DIR}:/config
      - ${MEDIA_TV_MOUNT_DIR}:/tv
      - ${DOWNLOADS_MOUNT_DIR}:/downloads
    ports:
      - ${SONARR_WEB_UI_PORT}:8989

  radarr:
    image: ghcr.io/linuxserver/radarr:4.1.0
    container_name: radarr
    restart: unless-stopped
    environment:
      PUID: ${APP_PUID}
      PGID: ${APP_PGID}
      TZ: ${HOST_TZ}
    volumes:
      - ${RADARR_CONFIG_MOUNT_DIR}:/config
      - ${MEDIA_MOVIES_MOUNT_DIR}:/movies
      - ${DOWNLOADS_MOUNT_DIR}:/downloads
    ports:
      - ${RADARR_WEB_UI_PORT}:7878

  lidarr:
    image: ghcr.io/linuxserver/lidarr:1.0.2
    container_name: lidarr
    restart: unless-stopped
    environment:
      PUID: ${APP_PUID}
      PGID: ${APP_PGID}
      TZ: ${HOST_TZ}
    volumes:
      - ${LIDARR_CONFIG_MOUNT_DIR}:/config
      - ${MEDIA_MUSIC_MOUNT_DIR}:/music
      - ${DOWNLOADS_MOUNT_DIR}:/downloads
    ports:
      - ${LIDARR_WEB_UI_PORT}:8686

  bazarr:
    image: ghcr.io/linuxserver/bazarr:1.1.1
    container_name: bazarr
    restart: unless-stopped
    environment:
      PUID: ${APP_PUID}
      PGID: ${APP_PGID}
      TZ: ${HOST_TZ}
    volumes:
      - ${BAZARR_CONFIG_MOUNT_DIR}:/config
      - ${MEDIA_MOVIES_MOUNT_DIR}:/movies
      - ${MEDIA_TV_MOUNT_DIR}:/tv
    ports:
      - ${BAZARR_WEB_UI_PORT}:6767