version: '3'

services:
  vpn:
    image: dperson/openvpn-client:latest
    container_name: deluge_vpn
    command: "-v ${REMOTE_SERVER};${REMOTE_USERNAME};${REMOTE_PASSWORD};${REMOTE_PORT}"
    cap_add:
      - net_admin
    security_opt:
      - label:disable
    environment:
      TZ: ${HOST_TZ}
    ports:
      - ${DELUGE_WEB_UI_PORT}:8112
    volumes:
      - /dev/net:/dev/net:z # tun device
      - ./services/deluge_vpn/vpn/ca.crt:/vpn/ca.crt
    restart: unless-stopped

  deluge:
    image: ghcr.io/linuxserver/deluge
    container_name: deluge
    network_mode: service:vpn
    environment:
      PUID: ${MEDIA_PUID}
      PGID: ${MEDIA_PGID}
      TZ: ${HOST_TZ}
      DELUGE_LOGLEVEL: ${DELUGE_LOGLEVEL}
    volumes:
      - ${DELUGE_CONFIG_MOUNT_DIR}:/config
      - ${MEDIA_DOWNLOADS_MOUNT_DIR}:/downloads
    restart: unless-stopped
    depends_on:
      - vpn

  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    environment:
      PUID: ${MEDIA_PUID}
      PGID: ${MEDIA_PGID}
      TZ: ${HOST_TZ}
    volumes:
      - ${JACKETT_CONFIG_MOUNT_DIR}:/config
      - ${TORRENT_DOWNLOADS_MOUNT_DIR}:/downloads
    ports:
      - ${JACKETT_WEB_UI_PORT}:9117
    restart: unless-stopped

  nzbget:
    image: ghcr.io/linuxserver/nzbget
    container_name: nzbget
    environment:
      PUID: ${MEDIA_PUID}
      PGID: ${MEDIA_PGID}
      TZ: ${HOST_TZ}
    volumes:
      - ${NZBGET_CONFIG_MOUNT_DIR}:/config
      - ${MEDIA_DOWNLOADS_MOUNT_DIR}:/downloads
    ports:
      - ${NZBGET_WEB_UI_PORT}:6789
    restart: unless-stopped

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      PUID: ${MEDIA_PUID}
      PGID: ${MEDIA_PGID}
      TZ: ${HOST_TZ}
    volumes:
      - ${SONARR_CONFIG_MOUNT_DIR}:/config
      - ${MEDIA_TV_MOUNT_DIR}:/tv
      - ${MEDIA_DOWNLOADS_MOUNT_DIR}:/downloads
    ports:
      - ${SONARR_WEB_UI_PORT}:8989
    restart: unless-stopped

  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      PUID: ${MEDIA_PUID}
      PGID: ${MEDIA_PGID}
      TZ: ${HOST_TZ}
    volumes:
      - ${RADARR_CONFIG_MOUNT_DIR}:/config
      - ${MEDIA_MOVIES_MOUNT_DIR}:/movies
      - ${MEDIA_DOWNLOADS_MOUNT_DIR}:/downloads
    ports:
      - ${RADARR_WEB_UI_PORT}:7878
    restart: unless-stopped

  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      PUID: ${MEDIA_PUID}
      PGID: ${MEDIA_PGID}
      TZ: ${HOST_TZ}
    volumes:
      - ${BAZARR_CONFIG_MOUNT_DIR}:/config
      - ${MEDIA_MOVIES_MOUNT_DIR}:/movies
      - ${MEDIA_TV_MOUNT_DIR}:/tv
    ports:
      - ${BAZARR_WEB_UI_PORT}:6767
    restart: unless-stopped

  plex:
    image: plexinc/pms-docker
    container_name: plex
    environment:
      PLEX_UID: ${MEDIA_PUID}
      PLEX_GID: ${MEDIA_PGID}
      ALLOWED_NETWORKS: ${PLEX_ALLOWED_NETWORKS}
    volumes:
      - ${PLEX_CONFIG_MOUNT_DIR}:/config
      - ${PLEX_TRANSCODE_MOUNT_DIR}:/transcode
      - ${MEDIA_MOVIES_MOUNT_DIR}:/movies
      - ${MEDIA_TV_MOUNT_DIR}:/tv
    ports:
      - ${PLEX_WEB_UI_PORT}:32400
    restart: unless-stopped
