version: '3'

services:
  tautulli:
    image: ghcr.io/linuxserver/tautulli:2.10.4
    container_name: tautulli
    restart: unless-stopped
    environment:
      PUID: ${APP_PUID}
      PGID: ${APP_PGID}
      TZ: ${HOST_TZ}
    volumes:
    - ${TAUTULLI_CONFIG_MOUNT_DIR}:/config
    ports:
    - ${TAUTULLI_WEB_PORT}:8181