version: '3'

services:
  registry:
    hostname: registry
    image: registry:2
    ports:
      - ${REGISTRY_PORT}:5000
    restart: unless-stopped
    volumes:
      - ${REGISTRY_MOUNT_DIR}:/var/lib/registry
