version: '3'

services:
  registry:
    image: registry:2
    container_name: registry
    restart: unless-stopped
    ports:
      - ${REGISTRY_PORT}:5000
    volumes:
      - ${REGISTRY_MOUNT_DIR}:/var/lib/registry
