version: '3'

services:
  plex:
    hostname: plex
    network_mode: host
    image: plexinc/pms-docker
    environment:
      - TZ=America/Vancouver
      - PLEX_CLAIM=$PLEX_CLAIM
    volumes:
      - plex_config:/config
      - plex_config:/transcode
      - /media/external/wd_hdd/Data:/data

  jenkins:
    hostname: jenkins
    image: jenkins/jenkins:lts
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      - JAVA_OPTS=-Duser.timezone=America/Vancouver
    volumes:
      - jenkins_home:/var/jenkins_home

  samba:
    hostname: samba
    image: dperson/samba:latest
    command: ["-u", "mrishab;$SAMBA_PASSWORD", "-s", "mrishab;/home/mrishab;yes;no;no;mrishab;mrishab;mrishab;Comment", "-w", "HOME", "-n"]
    network_mode: host
    volumes:
      - samba:/home/mrishab

volumes:
  plex_config:
  jenkins_home:
  samba:
