version: "3"

services:
    ombi:
        image: ghcr.io/linuxserver/ombi
        container_name: ombi
        restart: unless-stopped
        environment:
            PUID: ${OMBI_PUID}
            PGID: ${OMBI_PGID}
            TZ: ${HOST_TZ}
        volumes:
            - ${OMBI_CONFIG_MOUNT_DIR}:/config
        ports:
            - ${OMBI_WEB_PORT}:3579