version: "3"

services:
  ombi:
    image: ghcr.io/linuxserver/ombi:4.22.5
    container_name: ombi
    restart: unless-stopped
    environment:
      PUID: ${APP_PUID}
      PGID: ${APP_PGID}
      TZ: ${HOST_TZ}
    volumes:
      - ${OMBI_CONFIG_MOUNT_DIR}:/config
    ports:
      - ${OMBI_WEB_PORT}:3579