version: '3'

services:
  duplicati:
    container_name: duplicati
    image: ghcr.io/linuxserver/duplicati:latest
    restart: unless-stopped
    ports:
      - ${DUPLICATI_WEB_UI_PORT}:8200
    environment:
      PUID: ${APP_PUID}
      PGID: ${APP_PGID}
      TZ: ${HOST_TZ}
    volumes:
      - ${DUPLICATI_CONFIG_MOUNT_DIR}:/config
      - ${DUPLICATI_BACKUPS_MOUNT_DIR}:/backups
      - ${DUPLICATI_SOURCE_MOUNT_DIR}:/source
      - ${DUPLICATI_PRIMARY_RESTORE_MOUNT_DIR}:/primary_restore
      - ${DUPLICATI_SECONDARY_RESTORE_MOUNT_DIR}:/secondary_restore
