version: '3'

services:
  pg-admin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - ${PGADMIN_WEB_PORT}:443
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 443
    volumes:
      - ${PGADMIN_MOUNT_DIR}:/var/lib/pgadmin