version: '3'

services:
  pg-admin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - ${PGADMIN_WEB_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - ${PGADMIN_MOUNT_DIR}:/var/lib/pgadmin