version: '3'

services:
  sftpgo:
    image: drakkan/sftpgo:v2.5.4
    container_name: sftpgo
    restart: unless-stopped
    ports:
      - ${SFTP_WEB_PORT}:8080
      - ${SFTP_PORT}:2022
    volumes:
      - /srv/sftpgo
      - /var/lib/sftpgo
