version: '3'

services:
  jupyter:
    image: quay.io/jupyter/pytorch-notebook:cuda12-python-3.11.9
    container_name: jupyter
    restart: unless-stopped
    environment:
      JUPYTER_ENABLE_LAB: ${JUPYTER_ENABLE_LAB}
    volumes:
      - ${USER_HOME_MOUNT_DIR}:/home/jovyan
    ports:
      - ${JUPYTER_WEB_UI_PORT}:8888
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

