version: '3'

services:
  adguardhome:
    image: adguard/adguardhome:v0.107.0-b.4
    container_name: adguard
    restart: unless-stopped
    ports:
    volumes:
      - ${ADGUARD_WORK_MOUNT_DIR}:/opt/adguardhome/work
      - ${ADGUARD_CONF_MOUNT_DIR}:/opt/adguardhome/conf
    ports:
      - ${ADGUARD_WEBUI_PORT}:3000
      - ${ADGUARD_DNS_PORT}:53/tcp
      - ${ADGUARD_DNS_PORT}:53/udp
